### ISSUE TITLE
Project is not compiling because android include folders and libandroid.so

### ISSUE THREAD

**Issue by tuliomagalhaes** [Discordia/android-cmake-example#1]
I'm trying to compile but the android include folders are not present in the build and cmake cannot found the libandroid.so.

Can you help please?

**Comment by Discordia** [comment]
Sure, I can try to help but I will need more information. Have you done all the steps in the readme of this project? If so, what is the output of make?

**Comment by tuliomagalhaes** [comment]
Yes I have read.
I created two env. variables: ANDROID_NDK = PATH TO NDK and ANDROID_CMAKE = PATH TO
android.toolchain.cmake and android.apk.cmake.
And I do this in project folder:
mkdir build && cd build

cmake -DCMAKE_TOOLCHAIN_FILE=${ANDROID_CMAKE}/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug ..

make

And I get this log:

Scanning dependencies of target androidcmakeexample
[ 50%] Building CXX object CMakeFiles/androidcmakeexample.dir/src/main.cpp.o
In file included from /home/tulio/Projetos/Testes-CMake-Android/android-cmake-example/src/main.cpp:1:0:
/opt/android-ndk/sources/android/native_app_glue/android_native_app_glue.h:25:35: fatal error: android/configuration.h: No such file or directory
 #include <android/configuration.h>
                                   ^
compilation terminated.
CMakeFiles/androidcmakeexample.dir/build.make:57: recipe for target 'CMakeFiles/androidcmakeexample.dir/src/main.cpp.o' failed
make[2]: **\* [CMakeFiles/androidcmakeexample.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/androidcmakeexample.dir/all' failed
make[1]: **\* [CMakeFiles/androidcmakeexample.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Discordia** [comment]
I remember something about fighting with api levels when I were setting my project up. When doing the standalone toolchain (i.e.http://www.kandroid.org/ndk/docs/STANDALONE-TOOLCHAIN.html) what did you send in as --platform? I think I sent in android-9. If you are targeting something else you will probably have to set the ANDROID_API_LEVEL option in android-cmake to something matching. Thats all I can think of now.

**Comment by tuliomagalhaes** [comment]
Now I'm getting link error for all libraries:

/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_so.o: No such file or directory
/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_so.o: No such file or directory
/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llog
/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -landroid
/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lm
/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl

**Comment by Discordia** [comment]
I have not had these problems, but I googled it and found this: http://stackoverflow.com/questions/6881164/crtbegin-so-o-missing-for-android-toolchain-custom-build 

Maybe it helps?

**Comment by tuliomagalhaes** [comment]
I have discovered the cause of this errors, but I don't know why this occurs.
Solution: build using one api as parameter (example: ANDROID_NATIVE_API_LEVEL=android-9) and remove all flags.
For the first problem, setting api level ok.
For the second problem, remove all flags and all will be ok.
Thanks for the help.
