### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AndreyNeyvanov** [Discordia/android-cmake-example#2]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/myid/Work/android-cmake-example-master
[ 50%] Building CXX object CMakeFiles/androidcmakeexample.dir/src/main.cpp.o
In file included from /home/myid/Work/android-cmake-example-master/src/main.cpp:1:0:
/opt/Android_NDK/android-ndk-r9d/sources/android/native_app_glue/android_native_app_glue.h:25:35: fatal error: android/configuration.h: No such file or directory
compilation terminated.
make[2]: **\* [CMakeFiles/androidcmakeexample.dir/src/main.cpp.o] Error 1
make[1]: **\* [CMakeFiles/androidcmakeexample.dir/all] Error 2
make: **\* [all] Error 2

**Comment by AndreyNeyvanov** [comment]
[CMakeLists.txt](https://github.com/Discordia/android-cmake-example/files/263389/CMakeLists.txt)

**Comment by AndreyNeyvanov** [comment]
[build.sh.txt](https://github.com/Discordia/android-cmake-example/files/263392/build.sh.txt)

**Comment by Discordia** [comment]
I have no idea. Googling this I found this:
http://www.scriptscoop2.com/t/862f614a1245/not-able-to-build-android-ndk-project-fatal-error-android-configuratio.html

http://stackoverflow.com/questions/21903902/not-able-to-build-android-ndk-project-fatal-error-android-configuration-h-no-s

Maybe it helps.

**Comment by Discordia** [comment]
I think there is some information in this old closed issue that can help you:
https://github.com/Discordia/android-cmake-example/issues/1

**Comment by Discordia** [comment]
I'm closing this as I have not heard back and I do not think it is an issue rather missing documentation.
